# Generated by Django 5.0.7 on 2024-08-06 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
        ('teachers', '0004_alter_subjectregistration_scores'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectregistration',
            unique_together={('stud_name', 'subject_name', 'academic_year')},
        ),
    ]
