# Generated by Django 5.0.7 on 2024-08-06 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
        ('teachers', '0005_alter_subjectregistration_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectregistration',
            name='grade_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.grade'),
        ),
    ]
